### ISSUE TITLE
RISC.Mod does not belong here

### ISSUE THREAD

**Issue by schierlm** [io-core/System#1]
RISC.Mod is written in Oberon-2 (not Oberon-07) and therefore does not compile on Project Oberon.

Same for ORC.Mod in `io-core/Build` module.

**Comment by charlesap** [comment]
True. And since they are available elsewhere it is just confusing to keep them here. Perhaps in the future it will be instructive to reintroduce them in Oberon-07.

**Comment by schierlm** [comment]
When we have bigger file support (for disk images) we could even have a RISC emulator running on RISC (of course the emulated machine must have smaller screen and less RAM than the host)...
